### PR TITLE
[WIP]Testing golang-ci

### PR DESCRIPTION
**Pull request by muskankhedia**
Signed-off-by: muskankhedia <muskan.khedia2000@gmail.com>

Fixes: #84

### CODE REVIEW

**Comment by muskankhedia** [comment]
@Harkishen-Singh I was trying to reproduce issue #84 but as I see here GolangCI is working as expected in the PRs, it only checks the file updated in the particular PR and the GolangCI fail due to the vendor app in the previous PR makes no effect on the upcoming PR (if the files in the vendor app hasn't been changed).  Please correct me if I am wrong.

**Comment by muskankhedia** [comment]
Sure!

**Comment by Harkishen-Singh** [comment]
@muskankhedia, I see in other PRs, that the Golang CI is working as expected. You can go ahead with yr plans with this PR.

**Comment by muskankhedia** [comment]
It was just a testing PR for GoLang CI. As now GolangCI works well. It's not required anymore. We can close it.

**Pull request closed without merging**
