### PR TITLE
Merge BR-electron into bench-routes

### PR DESCRIPTION
**Pull request by aquibbaig**
**git** lets you add submodules referring to other repositories within a parent repository

Feat: Merged bench-routes-electron as dashboard inside bench-routes as a submodule, reconfigured prettier. 

### Motivation
Fixes the need to clone different repositories, also keeping track of two separate repositories. The older repository is still there preserving all the commit history.

Signed-off-by: Aquib Baig <aquibbaig97@gmail.com>

### CODE REVIEW

**Comment by Harkishen-Singh** [comment]
@aquibbaig I think this might make a reference copy of the bench-routes-electron project. What we aimed for was a complete integration of UI here and discontinuing the `bench-routes-electron` repo. Seeing the `merge-br-ui` branch seems like a reference to the electron repo.

**Comment by Harkishen-Singh** [comment]
@aquibbaig please have a look at [PR](https://github.com/zairza-cetb/bench-routes/pull/121). Does that meet the requirement?

**Comment by ganeshpatro321** [comment]
If this might help! https://stackoverflow.com/questions/1425892/how-do-you-merge-two-git-repositories

**Comment by Harkishen-Singh** [comment]
Yeah. I have used that only in my PR.

**Pull request closed without merging**
