### PR TITLE
Updated approach.md w/ reference to issue #171

### PR DESCRIPTION
**Pull request by RN0311**
Feel free to add/subtract changes!

### CODE REVIEW

**Comment by RN0311** [comment]
@aquibbaig : After running those commands on terminal, it shows "everything is up-to-date"

**Comment by ganeshpatro321** [comment]
Hi @RN0311 . In order to pass the DCO check, you need always ass -s flag while committing. DCO is called developer certificate of origin, and it asserts that you are the creator of the contribution. Make sure you use this flag in your further commits. And for this PR, please click on the details of the DCO check, or head over [here](https://github.com/zairza-cetb/bench-routes/pull/188/checks?check_run_id=539078009) , and run those commands to fix this. You just need to ammend the --signoff flag. Thanks.

**Comment by RN0311** [comment]
@ganeshpatro321 : Sure, thanks. I did, that.

**Comment by ganeshpatro321** [comment]
@RN0311 Can you rebase the master branch with yours. This PR has commits which are already in the target(master) branch.

**Comment by RN0311** [comment]
@ganeshpatro321 : Umm, legit I have no idea of which git-commands should I use in over here, tried googling, but bit confused. Can you help in here please! :)

**Comment by aquibbaig** [comment]
@RN0311 Congratulations on your contribution! 🎉 
Pro tip: 
- Next time do not commit with your `master` branch. For each issue no matter how much, it definitely makes sense to create individual branches that are named with respect to the issue/feature. 
- Also, you can use `git rebase` instead of `git merge` (That's just my personal preference).

**Pull request merged**
