### PR TITLE
Proper handling of runtime-exceptions in jitter and ping

### PR DESCRIPTION
**Pull request by suvidsahay**
Signed-off-by: suvidsahay <sahay.suvid61@gmail.com>

### CODE REVIEW

**Comment by suvidsahay** [comment]
Will this work for issue #115  @Harkishen-Singh  ?

**Comment by Harkishen-Singh** [comment]
@muskankhedia @aquibbaig Please have a look.

**Comment by Harkishen-Singh** [comment]
@suvidsahay Kindly execute `make fix` to fix all linting issues before staging the `git`.

[optional] Also, if possible, install `golanglint-ci` and then execute `make lint`.

**Comment by muskankhedia** [comment]
@suvidsahay The PR works well for me and also now the log is being displayed in a single line. Please fix the travis as mentioned by @Harkishen-Singh above, then it will be good to go.

**Comment by muskankhedia** [comment]
@suvidsahay Please make all the commits with signature, else the DCO test won't pass for the PR.

**Pull request merged**
