### PR TITLE
Error handling in ping/flood-ping/jitter functionality

### PR DESCRIPTION
**Pull request by Pratik32**
* Handling error cases while running 'ping' command
* Run CLIPing()/CLIFloodPing() as normal go functions and not
  as go routines.

Signed-off-by: Pratik Shinde <pratikshinde320@gmail.com>

Tested the code with socket tester.

### CODE REVIEW

**Comment by Pratik32** [comment]
Rebased my branch. Closed the previous PR.

**Comment by Harkishen-Singh** [comment]
@Pratik32 it would be good if you can install https://github.com/golangci/golangci-lint#install and run `make lint` before pushing the newer commits. That would ensure the build to pass.

steps:
```
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.20.0
golangci-lint --version
make lint
```

**Comment by Pratik32** [comment]
@Harkishen-Singh  Done.configured lint. This time travis CI build is failing for some other reason.

**Comment by Harkishen-Singh** [comment]
@Pratik32 have you done `make fix` before pushing?

**Comment by Pratik32** [comment]
@Harkishen-Singh , fixed the formatting issue too.

**Pull request merged**
