### PR TITLE
Shift to yarn

### PR DESCRIPTION
**Pull request by maheshschand**
This resolves the issue #176 .

### CODE REVIEW

**Comment by maheshschand** [comment]
@ganeshpatro321 @aquibbaig @Harkishen-Singh  I made necessary changes in this new pull request. Sorry, previous pull request was closed by me because I messed up everything. I opened a new pull request. Could you please review it?

**Comment by ganeshpatro321** [comment]
@maheshschand Please check why the build is failing. We will have to make this faster. Thanks

**Comment by ganeshpatro321** [comment]
`Cannot find type definition file for 'normalize-package-data'.  TS2688` This is the error I am getting while running `make test-views-v1.1` from your branch.

**Comment by aquibbaig** [comment]
Updates @maheshschand ?

**Comment by maheshschand** [comment]
I am unable to resolve issue. Can I get some help?

**Comment by ganeshpatro321** [comment]
Hi @maheshschand The build was failing as our travis config was not parallelized, and it wasnt using the correct version of node. However, now in the master branch, travis config is parallelized. Please merge the master branch and update you branch. Things should work. Thanks.

**Comment by maheshschand** [comment]
Thanks. I will update tomorrow.

**Pull request closed without merging**
