### PR TITLE
Refactor HTML test file

### PR DESCRIPTION
**Pull request by aquibbaig**
Refactor the HTML test file

Signed-off-by: Aquib Baig <aquibbaig97@gmail.com>

### CODE REVIEW

**Comment by aquibbaig** [comment]
@Harkishen-Singh @muskankhedia We need to update the selenium-tests accordingly. I will do that today, no worries

**Comment by Harkishen-Singh** [comment]
@aquibbaig Sure.

**Comment by Harkishen-Singh** [comment]
@aquibbaig just updating the `xpath` of the buttons should solve the entire issue.

**Comment by aquibbaig** [comment]
Screenshot 2019-12-01 at 1 59 22 PM

**Comment by Harkishen-Singh** [comment]
@aquibbaig the selenium test cases have been resolved. Please have a look.

Also, the new test ui is great. Thanks for this!

**Pull request merged**
