### PR TITLE
Public slack channel badge 

### PR DESCRIPTION
**Pull request by aquibbaig**
Adding links to the Slack channel in README

### CODE REVIEW

**Comment by aquibbaig** [comment]
Done in #57

**Comment by Harkishen-Singh** [comment]
@aquibbaig better if we add a statement, something like _join the discussions at ...._ along with the badge

**Comment by aquibbaig** [comment]
@Harkishen-Singh No problem

**Comment by aquibbaig** [comment]
@Harkishen-Singh Changing it to `Join the discussions on Slack`

**Comment by Harkishen-Singh** [comment]
Sure! sounds good.

**Pull request merged**
